#!/usr/bin/env python3
"""Render the Biologix discovery protocol into per-client setup files under ``clients/``.

The server already drives any client through the protocol gate (every result
names ``next_required_tool`` and quotes ``step_instructions``). These files make
the agent adopt the protocol from the first message in clients that read rules,
agents, or skills from disk:

    clients/AGENTS.md                         any AGENTS.md-aware tool (Codex, Cursor, Antigravity)
    clients/cursor/.cursor/...                Cursor: MCP config + always-on rule
    clients/claude-code-plugin/...            Claude Code plugin: MCP server, agent, skill
    clients/antigravity/.agents/...           Antigravity: mcp_config.json + always-on rule
    clients/chatgpt/README.md                 ChatGPT developer-mode connector + project instructions
    clients/grok/...                          xAI API remote MCP example

Usage::

    python scripts/build_client_adapters.py          # write
    python scripts/build_client_adapters.py --check  # exit 1 when clients/ is stale
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict

REPO_ROOT = Path(__file__).resolve().parents[1]
PROTOCOL_PATH = REPO_ROOT / "src" / "python" / "biologix_ai" / "protocol" / "PROTOCOL.md"
CLIENTS = REPO_ROOT / "clients"
MCP_URL = os.environ.get(
    "BIOLOGIX_MCP_URL", "https://muhammadhasyim--biologix-mcp-serve.modal.run/mcp"
)
GENERATED = (
    "<!-- Generated by scripts/build_client_adapters.py from "
    "src/python/biologix_ai/protocol/PROTOCOL.md. Edit PROTOCOL.md, then rerun. -->"
)
DESCRIPTION = (
    "Biologix discovery agent: plans polymer excipient formulations for a biologic "
    "(insulin, GLP-1 analogues, antibodies, enzymes, vaccines) with literature, PSMILES "
    "screening, OpenMM encapsulation, and retrosynthesis on the Biologix MCP server."
)
# Short enough for ChatGPT project instructions and Grok system prompts that
# should not carry the whole protocol; the server supplies the rest per step.
SHORT_INSTRUCTIONS = """You are the Biologix discovery agent. When the Biologix tools are available:
1. If the user has not given a biologic (name, PDB:chains, uniprot:ACCESSION, or sequence:...) and a polymer target or "suggest", ask only for those and wait.
2. Call begin_biologix_discovery first; it returns the full protocol. Follow it.
3. Call one Biologix tool at a time. Every result has protocol.next_required_tool, next_arguments, and step_instructions: call that tool next.
4. A result with status "running" and a job_id is not finished: call await_biologix_job(job_id).
5. Do not stop, summarize, or ask the user until protocol.user_stop_allowed is true or a tool fails. On a failure, show the exact error.
6. Write PSMILES and reaction extractions yourself. Never invent simulation, screening, or retrosynthesis results."""


def _protocol() -> str:
    return PROTOCOL_PATH.read_text(encoding="utf-8").strip()


def _json(data: object) -> str:
    return json.dumps(data, indent=2) + "\n"


def render() -> Dict[str, str]:
    """``{relative path under clients/: file content}``."""
    protocol = _protocol()
    files: Dict[str, str] = {}

    files["README.md"] = f"""{GENERATED}

# Biologix MCP client setup

Server: `{MCP_URL}` (Streamable HTTP, OAuth 2.1 with Dynamic Client Registration;
a bearer token also works). Every client gets the same 24 protocol tools, and the
server tells the model which tool comes next in every result, so any client works
without these files. They make the model adopt the protocol from the first message.

| Client | Copy | Auth |
|---|---|---|
| Claude (web, desktop) | Settings → Connectors → Add custom connector → the URL above. Optional: paste `chatgpt/README.md`'s instructions into Project instructions. | OAuth |
| Claude Code | `claude plugin install ./clients/claude-code-plugin` (or copy its `.mcp.json`) | `BIOLOGIX_MCP_TOKEN` env or OAuth |
| Cursor | `cursor/.cursor/` into your project | OAuth (Connect in MCP settings) |
| Antigravity | `antigravity/.agents/` into your workspace | bearer token in `mcp_config.json` |
| ChatGPT | `chatgpt/README.md` | OAuth |
| Grok (xAI API) | `grok/README.md` | bearer token |
| Codex and other AGENTS.md tools | `AGENTS.md` into your project root, plus that tool's MCP config | per tool |
"""

    files["AGENTS.md"] = f"{GENERATED}\n\n{protocol}\n"

    # Cursor
    files["cursor/.cursor/mcp.json"] = _json({"mcpServers": {"biologix": {"url": MCP_URL}}})
    files["cursor/.cursor/rules/biologix-discovery.mdc"] = (
        f"---\ndescription: {DESCRIPTION}\nalwaysApply: true\n---\n{GENERATED}\n\n{protocol}\n"
    )

    # Claude Code plugin
    files["claude-code-plugin/.claude-plugin/plugin.json"] = _json(
        {
            "name": "biologix",
            "version": "1.0.0",
            "description": DESCRIPTION,
            "author": {"name": "Biologix"},
        }
    )
    files["claude-code-plugin/.mcp.json"] = _json(
        {
            "mcpServers": {
                "biologix": {
                    "type": "http",
                    "url": "${BIOLOGIX_MCP_URL:-" + MCP_URL + "}",
                    "headers": {"Authorization": "Bearer ${BIOLOGIX_MCP_TOKEN}"},
                }
            }
        }
    )
    files["claude-code-plugin/agents/biologix-discovery.md"] = (
        f"---\nname: biologix-discovery\ndescription: {DESCRIPTION} Use for any request to "
        "stabilize, formulate, or deliver a biologic with polymers.\n---\n"
        f"{GENERATED}\n\n{protocol}\n"
    )
    files["claude-code-plugin/skills/biologix-discovery/SKILL.md"] = (
        f"---\nname: biologix-discovery\ndescription: {DESCRIPTION} Load whenever the user "
        "asks about polymer excipients, formulation, stabilization, or delivery of a "
        "biologic, or when Biologix MCP tools are available.\n---\n"
        f"{GENERATED}\n\n{protocol}\n"
    )

    # Antigravity (rules are capped at 12,000 characters)
    files["antigravity/.agents/mcp_config.json"] = _json(
        {
            "mcpServers": {
                "biologix": {
                    "serverUrl": MCP_URL,
                    "headers": {"Authorization": "Bearer <BIOLOGIX_MCP_TOKEN>"},
                }
            }
        }
    )
    files["antigravity/.agents/rules/biologix-discovery.md"] = (
        f"---\ntrigger: always_on\ndescription: {DESCRIPTION}\n---\n{GENERATED}\n\n{protocol}\n"
    )

    files["chatgpt/README.md"] = f"""{GENERATED}

# ChatGPT

1. Settings → Apps & Connectors → Advanced settings → turn on **Developer mode**.
2. Create a connector: name `Biologix`, MCP server URL `{MCP_URL}`, authentication **OAuth**.
   Leave the OAuth Client ID field empty; ChatGPT registers itself. Approve on the
   Biologix `/oauth/approve` page with your access token.
3. In a chat, enable the Biologix connector (the tools menu under **+**).
4. Optional: put this in the project's instructions. ChatGPT reads only the first 512
   characters of server instructions, so the server also repeats each step's
   instructions in every tool result.

```text
{SHORT_INSTRUCTIONS}
```
"""

    files["grok/README.md"] = f"""{GENERATED}

# Grok (xAI API)

xAI connects to the Biologix server itself through a remote MCP tool
(`type: "mcp"`, `server_url`, `server_label`, `authorization`). Use the protocol as
the system prompt: `grok_responses_example.py` sends `../AGENTS.md`, or the short
version below.

```json
{{
  "type": "mcp",
  "server_url": "{MCP_URL}",
  "server_label": "biologix",
  "authorization": "Bearer <BIOLOGIX_MCP_TOKEN>"
}}
```

```text
{SHORT_INSTRUCTIONS}
```
"""
    files["grok/grok_responses_example.py"] = f'''"""Run one Biologix turn with Grok through the xAI Responses API (OpenAI-compatible).

    pip install openai
    XAI_API_KEY=... BIOLOGIX_MCP_TOKEN=... python grok_responses_example.py "semaglutide, suggest"
"""

import os
import sys
from pathlib import Path

from openai import OpenAI

client = OpenAI(api_key=os.environ["XAI_API_KEY"], base_url="https://api.x.ai/v1")
protocol = (Path(__file__).resolve().parent.parent / "AGENTS.md").read_text(encoding="utf-8")
response = client.responses.create(
    model=os.environ.get("XAI_MODEL", "grok-4"),
    instructions=protocol,
    input=" ".join(sys.argv[1:]) or "I want to stabilize insulin; suggest polymers.",
    tools=[
        {{
            "type": "mcp",
            "server_url": os.environ.get("BIOLOGIX_MCP_URL", "{MCP_URL}"),
            "server_label": "biologix",
            "authorization": "Bearer " + os.environ["BIOLOGIX_MCP_TOKEN"],
        }}
    ],
)
print(response.output_text)
'''
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail when clients/ is out of date")
    args = parser.parse_args()
    stale = []
    for rel, content in render().items():
        path = CLIENTS / rel
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(rel)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    if stale:
        print("clients/ is stale; run scripts/build_client_adapters.py:\n  " + "\n  ".join(stale))
        return 1
    if not args.check:
        print(f"wrote {len(render())} files under {CLIENTS}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
